version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend/models/saved:/app/backend/models/saved
      - ./temp:/app/temp
    env_file:
      - .env
    restart: unless-stopped

  # If using a separate frontend container, uncomment this section
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped